# Generated by Django 5.1 on 2024-08-14 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='company_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('company_address', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_condactno', models.IntegerField()),
                ('owner_name', models.CharField(max_length=20)),
                ('owner_adharphoto', models.FileField(upload_to='')),
                ('company_username', models.CharField(max_length=20)),
                ('company_password', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ph_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('definition', models.CharField(max_length=500)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('company_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.company_reg')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.reg')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('delivery_date', models.CharField(max_length=15)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('payment_status', models.CharField(max_length=20, null=True)),
                ('purchase_date', models.CharField(max_length=20)),
                ('product_status', models.CharField(default='Order Placed', max_length=50, null=True)),
                ('shipping_status', models.CharField(default='at factory', max_length=30, null=True)),
                ('instruction', models.CharField(default='Your Order Has Been Successfully Placed', max_length=50, null=True)),
                ('refund_status', models.CharField(default='none', max_length=30, null=True)),
                ('company_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.company_reg')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.reg')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('total_price', models.IntegerField(default=500)),
                ('company_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.company_reg')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.reg')),
            ],
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('company_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.company_reg')),
            ],
        ),
        migrations.CreateModel(
            name='wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('total_price', models.IntegerField(default=500)),
                ('company_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.company_reg')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.reg')),
            ],
        ),
    ]
