# Generated by Django 5.1 on 2024-08-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_remove_order_city_remove_order_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
