# Generated by Django 5.1 on 2024-08-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=500),
        ),
    ]
