# Generated by Django 5.1 on 2024-08-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0005_cart_qty_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
