# Generated by Django 5.1 on 2024-08-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0006_remove_cart_qty_remove_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_pprice',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
