# Generated by Django 5.1 on 2024-08-21 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0007_order_total_pprice_order_total_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('delivery_date', models.CharField(max_length=15)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
                ('payment_status', models.CharField(max_length=20, null=True)),
                ('purchase_date', models.CharField(max_length=20)),
                ('product_status', models.CharField(default='Order Placed', max_length=50, null=True)),
                ('shipping_status', models.CharField(default='at factory', max_length=30, null=True)),
                ('instruction', models.CharField(default='Your Order Has Been Successfully Placed', max_length=50, null=True)),
                ('refund_status', models.CharField(default='none', max_length=30, null=True)),
                ('total_pprice', models.CharField(max_length=10, null=True)),
                ('total_quantity', models.CharField(max_length=10, null=True)),
                ('company_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.company_reg')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.reg')),
            ],
        ),
    ]
