# Generated by Django 5.1 on 2024-08-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0008_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_pprice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='order_cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order_cart',
            name='total_price',
        ),
    ]
