# Generated by Django 5.1 on 2024-08-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0009_remove_order_total_pprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_cart',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='delivery_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='purchase_date',
            field=models.CharField(max_length=50),
        ),
    ]
