# Generated by Django 5.1 on 2024-08-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0010_alter_order_cart_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_cart',
            name='total_pprice',
            field=models.IntegerField(default=0),
        ),
    ]
