# Generated by Django 5.1 on 2024-08-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0011_alter_order_cart_total_pprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
