# Generated by Django 5.1 on 2024-08-21 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0013_passwordreset_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset_c',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.company_reg'),
        ),
    ]
